// This file is auto-generated. Do not edit manually.
// Generated by syncgen - any changes will be overwritten.

export const schema = {
  tables: [
    {
      name: 'bullet_entry' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        bullet: { type: 'string' as const, optional: false },
        owner: { type: 'string' as const, recordId: true, optional: false },
        section_name: { type: 'string' as const, optional: false },
        sort_order: { type: 'number' as const, optional: true },
        cv_documents: { type: 'string' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'chat_message' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        content: { type: 'string' as const, optional: true },
        created_at: { type: 'string' as const, dateTime: true, optional: true },
        import_summary: { type: 'string' as const, optional: true },
        job_id: { type: 'string' as const, optional: true },
        owner: { type: 'string' as const, recordId: true, optional: true },
        role: { type: 'string' as const, optional: true },
        writing: { type: 'boolean' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'cv_document' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        include_phone: { type: 'boolean' as const, optional: true },
        owner: { type: 'string' as const, recordId: true, optional: false },
        pdf_url: { type: 'string' as const, optional: true },
        section_order: { type: 'string' as const, optional: true },
        selected_bullets: { type: 'string' as const, recordId: true, optional: true },
        selected_education: { type: 'string' as const, recordId: true, optional: true },
        selected_experience: { type: 'string' as const, recordId: true, optional: true },
        selected_projects: { type: 'string' as const, recordId: true, optional: true },
        selected_skills: { type: 'string' as const, recordId: true, optional: true },
        theme: { type: 'string' as const, optional: true },
        title: { type: 'string' as const, optional: false },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'education_entry' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        area: { type: 'string' as const, optional: true },
        degree: { type: 'string' as const, optional: true },
        end_date: { type: 'string' as const, optional: true },
        highlights: { type: 'string' as const, optional: true },
        institution: { type: 'string' as const, optional: false },
        location: { type: 'string' as const, optional: true },
        owner: { type: 'string' as const, recordId: true, optional: false },
        start_date: { type: 'string' as const, optional: true },
        cv_documents: { type: 'string' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'experience_entry' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        company: { type: 'string' as const, optional: false },
        end_date: { type: 'string' as const, optional: true },
        highlights: { type: 'string' as const, optional: true },
        location: { type: 'string' as const, optional: true },
        owner: { type: 'string' as const, recordId: true, optional: false },
        position: { type: 'string' as const, optional: true },
        start_date: { type: 'string' as const, optional: true },
        cv_documents: { type: 'string' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'jobs_agent' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        assigned_to: { type: 'string' as const, recordId: true, optional: false },
        created_at: { type: 'string' as const, dateTime: true, optional: true },
        errors: { type: 'string' as const, optional: false },
        max_retries: { type: 'number' as const, optional: false },
        path: { type: 'string' as const, optional: false },
        payload: { type: 'string' as const, optional: false },
        retries: { type: 'number' as const, optional: false },
        retry_strategy: { type: 'string' as const, optional: false },
        status: { type: 'string' as const, optional: false },
        updated_at: { type: 'string' as const, dateTime: true, optional: false },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'jobs_render' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        assigned_to: { type: 'string' as const, recordId: true, optional: false },
        created_at: { type: 'string' as const, dateTime: true, optional: true },
        errors: { type: 'string' as const, optional: false },
        max_retries: { type: 'number' as const, optional: false },
        path: { type: 'string' as const, optional: false },
        payload: { type: 'string' as const, optional: false },
        retries: { type: 'number' as const, optional: false },
        retry_strategy: { type: 'string' as const, optional: false },
        status: { type: 'string' as const, optional: false },
        updated_at: { type: 'string' as const, dateTime: true, optional: false },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'project_entry' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        end_date: { type: 'string' as const, optional: true },
        highlights: { type: 'string' as const, optional: true },
        location: { type: 'string' as const, optional: true },
        name: { type: 'string' as const, optional: false },
        owner: { type: 'string' as const, recordId: true, optional: false },
        start_date: { type: 'string' as const, optional: true },
        cv_documents: { type: 'string' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'skill_entry' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        details: { type: 'string' as const, optional: true },
        label: { type: 'string' as const, optional: false },
        owner: { type: 'string' as const, recordId: true, optional: false },
        cv_documents: { type: 'string' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'social_network' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        network: { type: 'string' as const, optional: false },
        network_username: { type: 'string' as const, optional: false },
        owner: { type: 'string' as const, recordId: true, optional: false },
        sort_order: { type: 'number' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
    {
      name: 'user' as const,
      columns: {
        id: { type: 'string' as const, recordId: true, optional: false },
        email: { type: 'string' as const, optional: true },
        location: { type: 'string' as const, optional: true },
        name: { type: 'string' as const, optional: true },
        phone: { type: 'string' as const, optional: true },
        profile_picture: { type: 'string' as const, optional: true },
        username: { type: 'string' as const, optional: false },
        website: { type: 'string' as const, optional: true },
        bullet_entries: { type: 'string' as const, optional: true },
        chat_messages: { type: 'string' as const, optional: true },
        cv_documents: { type: 'string' as const, optional: true },
        education_entries: { type: 'string' as const, optional: true },
        experience_entries: { type: 'string' as const, optional: true },
        project_entries: { type: 'string' as const, optional: true },
        skill_entries: { type: 'string' as const, optional: true },
        social_networks: { type: 'string' as const, optional: true },
      },
      primaryKey: ['id'] as const
    },
  ],
  relationships: [
    {
      from: 'bullet_entry' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'bullet_entry' as const,
      field: 'cv_documents' as const,
      to: 'cv_document' as const,
      cardinality: 'many' as const
    },
    {
      from: 'chat_message' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'cv_document' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'cv_document' as const,
      field: 'selected_bullets' as const,
      to: 'bullet_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'cv_document' as const,
      field: 'selected_education' as const,
      to: 'education_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'cv_document' as const,
      field: 'selected_experience' as const,
      to: 'experience_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'cv_document' as const,
      field: 'selected_projects' as const,
      to: 'project_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'cv_document' as const,
      field: 'selected_skills' as const,
      to: 'skill_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'education_entry' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'education_entry' as const,
      field: 'cv_documents' as const,
      to: 'cv_document' as const,
      cardinality: 'many' as const
    },
    {
      from: 'experience_entry' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'experience_entry' as const,
      field: 'cv_documents' as const,
      to: 'cv_document' as const,
      cardinality: 'many' as const
    },
    {
      from: 'project_entry' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'project_entry' as const,
      field: 'cv_documents' as const,
      to: 'cv_document' as const,
      cardinality: 'many' as const
    },
    {
      from: 'skill_entry' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'skill_entry' as const,
      field: 'cv_documents' as const,
      to: 'cv_document' as const,
      cardinality: 'many' as const
    },
    {
      from: 'social_network' as const,
      field: 'owner' as const,
      to: 'user' as const,
      cardinality: 'one' as const
    },
    {
      from: 'user' as const,
      field: 'bullet_entries' as const,
      to: 'bullet_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'user' as const,
      field: 'chat_messages' as const,
      to: 'chat_message' as const,
      cardinality: 'many' as const
    },
    {
      from: 'user' as const,
      field: 'cv_documents' as const,
      to: 'cv_document' as const,
      cardinality: 'many' as const
    },
    {
      from: 'user' as const,
      field: 'education_entries' as const,
      to: 'education_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'user' as const,
      field: 'experience_entries' as const,
      to: 'experience_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'user' as const,
      field: 'project_entries' as const,
      to: 'project_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'user' as const,
      field: 'skill_entries' as const,
      to: 'skill_entry' as const,
      cardinality: 'many' as const
    },
    {
      from: 'user' as const,
      field: 'social_networks' as const,
      to: 'social_network' as const,
      cardinality: 'many' as const
    },
  ],
  access: {
    account: {"signIn":{"params":{"password":{"type":"string","optional":false},"username":{"type":"string","optional":false}}},"signup":{"params":{"password":{"type":"string","optional":false},"username":{"type":"string","optional":false}}}},
  },
  buckets: [
  ],
  backends: {
    "agent": {
      outboxTable: 'jobs_agent' as const,
      routes: {
        "/chat": {
          args: {
          }
        },
        "/import/csv": {
          args: {
          }
        },
        "/import/linkedin": {
          args: {
          }
        },
      }
    },
    "render": {
      outboxTable: 'jobs_render' as const,
      routes: {
        "/render": {
          args: {
            "yaml_content": {
              type: 'string' as const,
              optional: false as const
            },
          }
        },
      }
    },
  },
} as const;

export type SchemaDefinition = typeof schema;


/**
 * The complete SurrealDB schema definition.
 * This constant contains the raw .surql schema file content.
 */
export const SURQL_SCHEMA = `-- ##################################################################
-- SCOPES & AUTHENTICATION
-- ##################################################################


-- ##################################################################
-- USER TABLE
-- ##################################################################

DEFINE TABLE user SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD username ON TABLE user TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 3
PERMISSIONS FOR select, create, update WHERE true;

DEFINE INDEX unique_username ON TABLE user FIELDS username UNIQUE;



DEFINE FIELD profile_picture ON TABLE user TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD name ON TABLE user TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD location ON TABLE user TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD email ON TABLE user TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD phone ON TABLE user TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD website ON TABLE user TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- SOCIAL NETWORK TABLE
-- ##################################################################

DEFINE TABLE social_network SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE social_network TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD network ON TABLE social_network TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD network_username ON TABLE social_network TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD sort_order ON TABLE social_network TYPE option<int>
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- EDUCATION ENTRY TABLE
-- ##################################################################

DEFINE TABLE education_entry SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE education_entry TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD institution ON TABLE education_entry TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD area ON TABLE education_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD degree ON TABLE education_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD start_date ON TABLE education_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD end_date ON TABLE education_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD location ON TABLE education_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD highlights ON TABLE education_entry TYPE option<array<string>>
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- EXPERIENCE ENTRY TABLE
-- ##################################################################

DEFINE TABLE experience_entry SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE experience_entry TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD company ON TABLE experience_entry TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD position ON TABLE experience_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD start_date ON TABLE experience_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD end_date ON TABLE experience_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD location ON TABLE experience_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD highlights ON TABLE experience_entry TYPE option<array<string>>
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- PROJECT ENTRY TABLE
-- ##################################################################

DEFINE TABLE project_entry SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE project_entry TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD name ON TABLE project_entry TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD start_date ON TABLE project_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD end_date ON TABLE project_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD location ON TABLE project_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD highlights ON TABLE project_entry TYPE option<array<string>>
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- SKILL ENTRY TABLE
-- ##################################################################

DEFINE TABLE skill_entry SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE skill_entry TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD label ON TABLE skill_entry TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD details ON TABLE skill_entry TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- BULLET ENTRY TABLE
-- ##################################################################

DEFINE TABLE bullet_entry SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE bullet_entry TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD section_name ON TABLE bullet_entry TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD bullet ON TABLE bullet_entry TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD sort_order ON TABLE bullet_entry TYPE option<int>
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- CHAT MESSAGE TABLE
-- ##################################################################

DEFINE TABLE chat_message SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE chat_message TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD role ON TABLE chat_message TYPE option<string>
ASSERT $value IN ["user", "assistant"]
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD content ON TABLE chat_message TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD writing ON TABLE chat_message TYPE option<bool>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD job_id ON TABLE chat_message TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD import_summary ON TABLE chat_message TYPE option<object> FLEXIBLE
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD created_at ON TABLE chat_message TYPE option<datetime>
VALUE time::now()
PERMISSIONS FOR select, create, update WHERE true;

-- ##################################################################
-- CV DOCUMENT TABLE
-- ##################################################################

DEFINE TABLE cv_document SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD owner ON TABLE cv_document TYPE option<record<user>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD title ON TABLE cv_document TYPE option<string>
ASSERT $value != NONE AND string::len($value) > 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD theme ON TABLE cv_document TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD section_order ON TABLE cv_document TYPE option<array<string>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD selected_education ON TABLE cv_document TYPE option<array<record<education_entry>>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD selected_experience ON TABLE cv_document TYPE option<array<record<experience_entry>>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD selected_projects ON TABLE cv_document TYPE option<array<record<project_entry>>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD selected_skills ON TABLE cv_document TYPE option<array<record<skill_entry>>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD selected_bullets ON TABLE cv_document TYPE option<array<record<bullet_entry>>>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD include_phone ON TABLE cv_document TYPE option<bool>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD pdf_url ON TABLE cv_document TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;



-- Backend Schema: agent
-- ##################################################################
-- AGENT API OUTBOX TABLE
-- ##################################################################

DEFINE TABLE jobs_agent SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD assigned_to ON TABLE jobs_agent TYPE option<record>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD path ON TABLE jobs_agent TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD payload ON TABLE jobs_agent TYPE any
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD retries ON TABLE jobs_agent TYPE option<int> DEFAULT ALWAYS 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD max_retries ON TABLE jobs_agent TYPE option<int> DEFAULT ALWAYS 3;

DEFINE FIELD retry_strategy ON TABLE jobs_agent TYPE option<string> DEFAULT ALWAYS "linear"
ASSERT $value IN ["linear", "exponential"]
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD status ON TABLE jobs_agent TYPE option<string> DEFAULT ALWAYS "pending"
ASSERT $value IN ["pending", "processing", "success", "failed"]
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD errors ON TABLE jobs_agent TYPE option<array<object>> DEFAULT ALWAYS []
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD updated_at ON TABLE jobs_agent TYPE option<datetime>
DEFAULT ALWAYS time::now()
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD created_at ON TABLE jobs_agent TYPE option<datetime>
VALUE time::now()
PERMISSIONS FOR select, create, update WHERE true;

-- Backend Schema: render
-- ##################################################################
-- API OUTBOX TABLE
-- ##################################################################

DEFINE TABLE jobs_render SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD assigned_to ON TABLE jobs_render TYPE option<record>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD path ON TABLE jobs_render TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD payload ON TABLE jobs_render TYPE any
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD retries ON TABLE jobs_render TYPE option<int> DEFAULT ALWAYS 0
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD max_retries ON TABLE jobs_render TYPE option<int> DEFAULT ALWAYS 3;

DEFINE FIELD retry_strategy ON TABLE jobs_render TYPE option<string> DEFAULT ALWAYS "linear"
ASSERT $value IN ["linear", "exponential"]
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD status ON TABLE jobs_render TYPE option<string> DEFAULT ALWAYS "pending"
ASSERT $value IN ["pending", "processing", "success", "failed"]
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD errors ON TABLE jobs_render TYPE option<array<object>> DEFAULT ALWAYS []
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD updated_at ON TABLE jobs_render TYPE option<datetime>
DEFAULT ALWAYS time::now()
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD created_at ON TABLE jobs_render TYPE option<datetime>
VALUE time::now()
PERMISSIONS FOR select, create, update WHERE true;

-- ==================================================
-- SPOOKY INCANTATION
-- The Registry of active Live Queries (Incantations).
-- Moved to meta_tables_client.surql and meta_tables_remote.surql
-- ==================================================

-- ==================================================
-- SPOOKY SCHEMA
-- The provisioned schema state for the database. Currently only used in local cache.
-- Used in local-migrator.ts
-- ==================================================

DEFINE TABLE IF NOT EXISTS _spooky_schema SCHEMAFULL;
DEFINE FIELD IF NOT EXISTS id ON _spooky_schema TYPE string;
DEFINE FIELD IF NOT EXISTS hash ON _spooky_schema TYPE string;
DEFINE FIELD IF NOT EXISTS created_at ON _spooky_schema TYPE datetime VALUE time::now();
DEFINE INDEX IF NOT EXISTS unique_hash ON _spooky_schema FIELDS hash UNIQUE;

-- ==================================================
-- SPOOKY STREAM PROCESSOR STATE
-- Stores the local state of the stream processor (DBSP)
-- ==================================================

DEFINE TABLE IF NOT EXISTS _spooky_stream_processor_state SCHEMALESS
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD IF NOT EXISTS id ON _spooky_stream_processor_state TYPE string;
DEFINE FIELD IF NOT EXISTS state ON _spooky_stream_processor_state TYPE string;
DEFINE FIELD IF NOT EXISTS updated_at ON _spooky_stream_processor_state TYPE datetime VALUE time::now();

-- ==================================================
-- SPOOKY INCANTATION
-- The Registry of active Live Queries (Incantations).
-- ==================================================

DEFINE TABLE _spooky_query SCHEMALESS
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD surql ON TABLE _spooky_query TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD localArray ON TABLE _spooky_query TYPE any
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD remoteArray ON TABLE _spooky_query TYPE any
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD lastActiveAt ON TABLE _spooky_query TYPE option<datetime> DEFAULT time::now()
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD ttl ON TABLE _spooky_query TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

DEFINE FIELD tableName ON TABLE _spooky_query TYPE option<string>
PERMISSIONS FOR select, create, update WHERE true;

-- ==================================================
-- SPOOKY EVENTS
-- Stores create, update, and delete events
-- ==================================================

DEFINE TABLE _spooky_pending_mutations SCHEMAFULL
PERMISSIONS FOR select, create, update, delete WHERE true;

DEFINE FIELD IF NOT EXISTS id ON _spooky_pending_mutations TYPE string;

DEFINE FIELD IF NOT EXISTS mutationType ON _spooky_pending_mutations TYPE string
PERMISSIONS FOR select, create, update WHERE true;

-- The target record ID (for update/delete) - maps to 'id' in the event object
DEFINE FIELD IF NOT EXISTS recordId ON _spooky_pending_mutations TYPE option<record>
PERMISSIONS FOR select, create, update WHERE true;

-- The data payload (for create/update)
DEFINE FIELD IF NOT EXISTS data ON _spooky_pending_mutations TYPE option<object> FLEXIBLE
PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE _spooky_pending_mutations TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE _spooky_query TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE _spooky_schema TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE _spooky_stream_processor_state TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE bullet_entry TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE chat_message TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE cv_document TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE education_entry TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE experience_entry TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE jobs_agent TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE jobs_render TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE project_entry TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE skill_entry TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE social_network TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;
DEFINE FIELD spooky_rv ON TABLE user TYPE int DEFAULT 0 PERMISSIONS FOR select, create, update WHERE true;


-- ==================================================
-- AUTO-GENERATED SPOOKY EVENTS
-- ==================================================

-- Table: bullet_entry Client Mutation
DEFINE EVENT OVERWRITE _spooky_bullet_entry_client_mutation ON TABLE bullet_entry
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: bullet_entry Client Deletion
DEFINE EVENT OVERWRITE _spooky_bullet_entry_client_delete ON TABLE bullet_entry
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: chat_message Client Mutation
DEFINE EVENT OVERWRITE _spooky_chat_message_client_mutation ON TABLE chat_message
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: chat_message Client Deletion
DEFINE EVENT OVERWRITE _spooky_chat_message_client_delete ON TABLE chat_message
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: cv_document Client Mutation
DEFINE EVENT OVERWRITE _spooky_cv_document_client_mutation ON TABLE cv_document
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: cv_document Client Deletion
DEFINE EVENT OVERWRITE _spooky_cv_document_client_delete ON TABLE cv_document
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: education_entry Client Mutation
DEFINE EVENT OVERWRITE _spooky_education_entry_client_mutation ON TABLE education_entry
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: education_entry Client Deletion
DEFINE EVENT OVERWRITE _spooky_education_entry_client_delete ON TABLE education_entry
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: experience_entry Client Mutation
DEFINE EVENT OVERWRITE _spooky_experience_entry_client_mutation ON TABLE experience_entry
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: experience_entry Client Deletion
DEFINE EVENT OVERWRITE _spooky_experience_entry_client_delete ON TABLE experience_entry
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: jobs_agent Client Mutation
DEFINE EVENT OVERWRITE _spooky_jobs_agent_client_mutation ON TABLE jobs_agent
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: jobs_agent Client Deletion
DEFINE EVENT OVERWRITE _spooky_jobs_agent_client_delete ON TABLE jobs_agent
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: jobs_render Client Mutation
DEFINE EVENT OVERWRITE _spooky_jobs_render_client_mutation ON TABLE jobs_render
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: jobs_render Client Deletion
DEFINE EVENT OVERWRITE _spooky_jobs_render_client_delete ON TABLE jobs_render
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: project_entry Client Mutation
DEFINE EVENT OVERWRITE _spooky_project_entry_client_mutation ON TABLE project_entry
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: project_entry Client Deletion
DEFINE EVENT OVERWRITE _spooky_project_entry_client_delete ON TABLE project_entry
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: skill_entry Client Mutation
DEFINE EVENT OVERWRITE _spooky_skill_entry_client_mutation ON TABLE skill_entry
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: skill_entry Client Deletion
DEFINE EVENT OVERWRITE _spooky_skill_entry_client_delete ON TABLE skill_entry
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: social_network Client Mutation
DEFINE EVENT OVERWRITE _spooky_social_network_client_mutation ON TABLE social_network
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: social_network Client Deletion
DEFINE EVENT OVERWRITE _spooky_social_network_client_delete ON TABLE social_network
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};

-- Table: user Client Mutation
DEFINE EVENT OVERWRITE _spooky_user_client_mutation ON TABLE user
WHEN $before != $after AND $event != "DELETE"
THEN {
    -- No-op for now. Client mutation sync logic moved to DBSP.
};

-- Table: user Client Deletion
DEFINE EVENT OVERWRITE _spooky_user_client_delete ON TABLE user
WHEN $event = "DELETE"
THEN {
    -- No-op for now.
};
`;
